### ISSUE TITLE
RubyNLP

### ISSUE THREAD

**Issue by arbox** [regexident/lasean#1]
Dear Vincent ,

we've recently added your project to our RubyNLP list: https://github.com/arbox/nlp-with-ruby

I wonder if you want to participate in the Ruby for NLP network. You could do this in a very simple step by adding the `rubynlp` topic to your GitHub repository. 

Thank you for the project!

**Comment by regexident** [comment]
Cool, thanks!

I've added `rubynlp`, `latent-semantic-analysis`, `lsa`, `ruby` as topics to improve discoverability. :)

Thanks for checking out "lasean", much appreciated!
